FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 6054

CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "6054", "--poll", "2000"]
